var allLinks = document.links;
allLinks[0].onclick=function(){
    $('.tabContent').css({
        'display':'none'
    });
    $('#tab0').css({
        'display':'block'
    });
}
allLinks[1].onclick=function(){
    $('.tabContent').css({
        'display':'none'
    });
    $('#tab1').css({
        'display':'block'
    });
}
allLinks[2].onclick=function(){
    $('.tabContent').css({
        'display':'none'
    });
    $('#tab2').css({
        'display':'block'
    });
}
allLinks[3].onclick=function(){
    $('.tabContent').css({
        'display':'none'
    });
    $('#tab3').css({
        'display':'block'
    });
}   
allLinks[4].onclick=function(){
    $('.tabContent').css({
        'display':'none'
    });
    $('#tab4').css({
        'display':'block'
    });
}
allLinks[5].onclick=function(){
    $('.tabContent').css({
        'display':'none'
    });
    $('#tab5').css({
        'display':'block'
    });
}
allLinks[6].onclick=function(){
    $('.tabContent').css({
        'display':'none'
    });
    $('#tab6').css({
        'display':'block'
    });
}
allLinks[7].onclick=function(){
    $('.tabContent').css({
        'display':'none'
    });
    $('#tab7').css({
        'display':'block'
    });
}
