# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-12 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='eid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
