# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-14 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_employee_eid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='c_leave',
            field=models.IntegerField(default=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='s_leave',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
    ]
