# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-23 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_r_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dept',
            field=models.CharField(choices=[('BA', 'Business Analysis Team'), ('dev', 'Developer'), ('QA', 'Quality Team')], default='BA', max_length=3),
        ),
    ]
