# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-20 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20161220_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a_leave',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='r_leave',
            name='halfday',
        ),
        migrations.AddField(
            model_name='r_leave',
            name='reason',
            field=models.CharField(default='sick', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='r_leave',
            name='l_type',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='a_leave',
        ),
    ]
