# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-23 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_employee_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='r_leave',
            name='name',
            field=models.CharField(default=' ', max_length=25),
        ),
    ]
