# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-23 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_r_leave_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r_leave',
            name='l_type',
            field=models.CharField(choices=[('SL', 'sick leave'), ('CL', 'Casaul leave')], default='CL', max_length=10),
        ),
    ]
