# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-23 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_auto_20161223_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='r_leave',
            name='no_of_days',
            field=models.IntegerField(default=0),
        ),
    ]
