# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-24 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_r_leave_no_of_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='r_leave',
            name='name',
        ),
    ]
