# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-24 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_remove_r_leave_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='r_leave',
            name='confirmation',
            field=models.IntegerField(default=0),
        ),
    ]
