# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-25 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_r_leave_confirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='public_holidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
            ],
        ),
    ]
