# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-25 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_public_holidays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='r_leave',
            name='no_of_days',
        ),
    ]
