# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-25 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_remove_r_leave_no_of_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='r_leave',
            name='no_of_days',
            field=models.IntegerField(default=0),
        ),
    ]
