# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-28 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_team_lead_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='r_leave',
            name='id',
        ),
        migrations.AddField(
            model_name='r_leave',
            name='l_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
