# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-17 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_auto_20161228_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='elg_c_cre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='elg_s_cre',
            field=models.BooleanField(default=False),
        ),
    ]
