# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-18 18:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0018_auto_20170117_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='att_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'A'), (1, 'P'), (2, 'SL'), (3, 'CL'), (4, 'EL'), (5, 'PC')], default=0)),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='managedby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='team_lead',
        ),
        migrations.AddField(
            model_name='employee',
            name='j_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='employee',
            name='t_date',
            field=models.DateField(default=datetime.date(2100, 1, 1)),
        ),
        migrations.AlterField(
            model_name='r_leave',
            name='l_type',
            field=models.CharField(choices=[('SL', 'sick leave'), ('CL', 'Casaul leave'), ('EL', 'Earned Leave')], default='CL', max_length=10),
        ),
        migrations.AddField(
            model_name='managedby',
            name='eid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee'),
        ),
    ]
