# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-18 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_auto_20170118_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
        migrations.DeleteModel(
            name='admin',
        ),
    ]
