# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-18 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='admins',
        ),
    ]
