# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-18 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_auto_20170118_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='salary',
            new_name='e_leave',
        ),
        migrations.AddField(
            model_name='employee',
            name='fname',
            field=models.CharField(default='firstname', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='lname',
            field=models.CharField(default='lastname', max_length=20),
            preserve_default=False,
        ),
    ]
