# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-18 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_auto_20170118_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='c_leave',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='present',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='s_leave',
            field=models.IntegerField(default=6),
        ),
    ]
